server:
  port: 8888

spring:
  redis:
    #Redis数据库索引（默认为0）
    database: 0
    host: 192.168.153.130
    port: 6379
    #密码默认为空
    password: loj896
#    pool:
#      #  连接池最大连接数（使用负值表示没有限制）
#      max-active: 8
#      # 连接池最大阻塞等待时间（使用负值表示没有限制）
#      max-wait: -1
#      # 连接池中的最大空闲连接
#      max-idle: 8
#      # 连接池中的最小空闲连接
#      min-idle: 0
    # 连接超时时间（毫秒）
    timeout: 100000

#log4j:
#  rootCategory: DEBUG,stdout