## mysql 的数据库配置
##spring:
##  datasource:
##    url: jdbc:mysql://localhost:3306/lixiang?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
##    username: root
##    password: loj896
##    driver-class-name: com.mysql.jdbc.Driver
##
###热部署
##devtools:
##  restart:
##    enabled: true #热部署生效
##    #设置重启的目录
##    additional-paths: src/main/java
##    exclude: WEB-INF/** #classpath目录下的WEB-INF文件夹内容修改不重启

spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mydb?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: loj896
    tomcat:
      initialSize: 1
      min-idle: 1
      max-idle: 20
      max-wait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 30000
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false

mybatis:
#  mapperLocations: classpath:mapper/*.xml
  mapper-locations: classpath:mapper/*.xml
  typeAliasesPackage: com.example.springbootweb.model
  mybatis.config: classpath:mapper/config/*.xml
  mybatis.typeHandlersPackage: com.example.springbootweb.handlers

#logging:
#  level:
#    java.sql.PreparedStatement: debug
#  file: logs/demo.log
#引入日志配置文件
#logging:
#  config: classpath:log4j2.yml

book:
  name: test
  author: loj

